logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG
server:
  error:
    include-stacktrace: never
    include-binding-errors: always
    include-exception: true
    include-message: always
spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

app:
  auth:
    tokenSecret: trokuttrokuttrokuttrokuttrokuttrokuttrokuttrokuttrokuttrokuttrokuttrokuttrokuttrokuttrokut
    tokenExpirationDays: 3
  cors:
    allowedOrigins: http://localhost:5173
